name: Exemplo ENV
on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: "Teste de env do workflow"
jobs:
  teste-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Valor env do job"

    steps:
      - name: Execução
        env:
          ENV_ACTION: "env da minha action"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"
  teste-env-dois:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Valor env do job teste dois"

    steps:
      - name: Execução
        env:
          ENV_ACTION: "env da minha action"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
